---
- name: install apache server
  apt:
          name: apache2
          state: present
- name: start and enaled apache at boot
  service:
          name: apache2
          state: started
          enabled: yes
 
